package auth

const (
	ERR_USER              = "ERR_USER"
	ERR_BAN_USER          = "ERR_BAN_USER"
	ERR_TOKEN             = "ERR_TOKEN"
	ERR_SESSION           = "ERR_SESSION"
	ERR_USER_NOT_FOUND    = "ERR_USER_NOT_FOUND"
	ERR_SESSION_NOT_FOUND = "ERR_SESSION_NOT_FOUND"
	ERR_SESSION_EXPIRED   = "ERR_SESSION_EXPIRED"
	ERR_SESSION_INVALID   = "ERR_SESSION_INVALID"
)
