app:
  name: sync-backend
  version: 0.0.1
  description: A backend service for "Sync" social media app

server:
  host: ${HOST}
  port: ${PORT}
  env: ${ENV}
  read_timeout: 60s
  write_timeout: 60s
  idle_timeout: 60s
  max_header_bytes: 1048576
  max_connections: 1000
  max_idle_connections: 1000
  request_timeout: 60s
  max_request_size: 1048576
  max_response_size: 1048576

api:
  version: 1
  prefix: /api
  rate_limit:
    enabled: true
    max_requests: 1000
    window: 1m
    burst: 2000
  cors:
    enabled: true
    allow_origin: "*"
    allow_methods: GET, POST, PUT, DELETE, OPTIONS
    allow_headers: Content-Type, Authorization, X-Request-ID, X-Requested-With
    expose_headers: Content-Type, Authorization, X-Request-ID, X-Requested-With
    max_age: 86400
    allow_credentials: true
