auth:
  jwt:
    expiration: 1h
    issuer: "your-issuer"
    audience: "your-audience"
    algorithm: "RS256"
    access_token_expiry: 1h
    refresh_token_expiry: 30d
    private_key_path: keys/private.pem
    public_key_path: keys/public.pem

  password:
    min_length: 8
    max_length: 64
    require_special_characters: true
    require_numbers: true
    require_uppercase: true
    require_lowercase: true
    history_count: 5
    expiration: 90d
    lockout_threshold: 5
    lockout_duration: 30m
    reset_token_expiry: 1h
    reset_token_length: 32
    reset_token_characters: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

  verification:
    require_email_verification: true
    email_verification_expiry: 24h
    verification_token_length: 32

  password-reset:
    require_password_reset: true
    password_reset_expiry: 24h
    password_reset_token_length: 32

  csrf:
    token_length: 32
    token_expiry: 15m
    token_storage: in-memory # in-memory, redis, database

  rate_limit:
    login:
      requests: 5
      duration: 1m
    registration:
      requests: 3
      duration: 1m
    general:
      requests: 1000
      duration: 10s
