log:
  output: stdout # stdout, file
  file_path: /logs/service.log # Only if output is file

  fields:
    service: sync-backend # Name of the service
    environment: ${ENV} # Environment (e.g., production, staging, development)

  # Hide sensitive data in logs
  sanitize:
    fields:
      - password
      - token
      - authorization
      - cookie

  # Special handling for HTTP request logging
  http:
    enabled: true
    level: info
    body_limit: 1000 # Max number of characters to log from body
    headers:
      include:
        - User-Agent
        - Content-Type
        - X-Request-ID
      exclude:
        - Authorization
        - Cookie

  # Performance-related settings
  performance:
    sampling_rate: 1.0 # Log all requests
    slow_threshold: 500ms # Log requests taking longer than this

  # Advanced features
  stacktrace:
    enabled: true
    level: error # Only include stack traces for error level and above

  rotation:
    enabled: true
    max_size: 100 # MB
    max_age: 30 # days
    max_backups: 10
    compress: true
